from __future__ import annotations

TUTORIALS = [
    {
        "key": "start",
        "title": "01 从数据结构开始",
        "why": "分析前先确认采样率、通道排列、数据类型、单位与时间轴。错误的通道数会让整个二进制文件被错误重排。",
        "input": "记录系统原始文件、探针信息、事件日志",
        "output": "只读数据源与 NeuroFlow 项目清单",
        "checks": "文件大小是否匹配；采样率是否可信；事件单位是秒、毫秒还是采样点",
        "reference": "IBL ALF data structure; SpikeInterface extractors",
    },
    {
        "key": "qc",
        "title": "02 原始信号质控",
        "why": "坏通道、饱和、工频和瞬时伪迹会影响参考、阈值检测和 sorting。",
        "input": "原始宽带电压",
        "output": "通道 RMS、频谱、饱和计数、排除建议",
        "checks": "异常是否局限于单通道；是否与运动或刺激同时发生；不要把真实高振幅 spike 当作伪迹",
        "reference": "SpikeInterface quality-control workflow",
    },
    {
        "key": "preprocess",
        "title": "03 预处理不是固定配方",
        "why": "Spike 与 LFP 的频段和生物物理意义不同。滤波、重参考和伪迹处理必须按分析对象选择。",
        "input": "原始电压与坏通道列表",
        "output": "处理预览或 sorter 配置",
        "checks": "避免重复滤波；检查边缘效应；先预览再对全量数据执行",
        "reference": "Kilosort4 preprocessing; LFP methodological reviews",
    },
    {
        "key": "sorting",
        "title": "04 Spike sorting 与验证",
        "why": "Sorter 将混合电压中的 spike 分配给候选 unit，但自动输出不等于可靠单神经元。",
        "input": "高采样率多通道记录与探针几何",
        "output": "spike times、cluster IDs、templates",
        "checks": "查看漂移、重复 unit、漏检、ISI 违例和波形稳定性",
        "reference": "Kilosort4; IBL spike-sorting benchmark",
    },
    {
        "key": "events",
        "title": "05 行为、TTL 与统一时间轴",
        "why": "事件对齐决定神经活动发生在行为之前还是之后。漏脉冲与时钟漂移不能靠画图掩盖。",
        "input": "spike 秒时间、TTL、行为事件与视频帧",
        "output": "trial 表和统一秒时间轴",
        "checks": "匹配数量、残差、漂移趋势、丢帧与重复事件",
        "reference": "IBL ALF trials object and synchronization",
    },
    {
        "key": "statistics",
        "title": "06 从图到统计证据",
        "why": "先定义样本单位与重复测量结构，再选择检验。unit、session 和动物不能随意当作独立样本。",
        "input": "trial 级指标与条件标签",
        "output": "效应量、置信区间、p/q 值与检验假设",
        "checks": "配对关系、多重比较、伪重复、分布假设与效应量",
        "reference": "Permutation tests; hierarchical analysis; BH FDR",
    },
    {
        "key": "decoding",
        "title": "07 神经解码与数据泄漏",
        "why": "解码回答神经活动能否预测标签，不自动证明脑区编码了某个抽象变量。",
        "input": "trial × feature 矩阵与标签",
        "output": "交叉验证准确率、AUC、混淆矩阵、置换零分布",
        "checks": "标准化必须在训练折内；同一 session/动物需分组拆分；报告 shuffle 基线",
        "reference": "IBL brain-wide map decoding analyses",
    },
    {
        "key": "figures",
        "title": "08 论文图与可复现导出",
        "why": "论文图需要可编辑、可追溯，并能找到生成它的输入、参数、统计表和软件版本。",
        "input": "分析对象、统计结果与绘图规范",
        "output": "PNG/SVG/PDF、绘图数据、Methods 与 workflow",
        "checks": "坐标与单位、误差定义、颜色可辨识性、统计标注来源",
        "reference": "IBL Brain-Wide Map 2025 figure organization",
    },
]
