from __future__ import annotations

TUTORIALS = [
    {
        "key": "import",
        "title": "01 从数据结构开始",
        "title_en": "01 Start with the data structure",
        "why": "分析前先确认采样率、通道排列、数据类型、单位与时间轴。错误的通道数会让整个二进制文件被错误重排。",
        "why_en": "Confirm sampling rate, channel order, dtype, units, and time base before analysis. A wrong channel count reshapes the entire binary stream incorrectly.",
        "input": "记录系统原始文件、探针信息、事件日志",
        "input_en": "Raw acquisition files, probe information, and event logs",
        "output": "只读数据源与 NeuroEphys AI 项目清单",
        "output_en": "Read-only source links and a NeuroEphys AI project manifest",
        "checks": "核对文件大小、采样率、通道数、数据类型，以及事件单位是秒、毫秒还是采样点。导入后先观察波形是否符合预期。",
        "checks_en": "Check file size, rate, channel count, dtype, and whether events use seconds, milliseconds, or samples. Inspect traces immediately after import.",
        "reference": "SpikeInterface extractors; IBL ALF data model",
    },
    {
        "key": "qc",
        "title": "02 原始信号质控",
        "title_en": "02 Raw-signal quality control",
        "why": "坏通道、饱和、工频和瞬时伪迹会改变参考信号、检测阈值和 sorting 结果。",
        "why_en": "Bad channels, saturation, line noise, and transients alter referencing, detection thresholds, and sorting results.",
        "input": "原始宽带电压",
        "input_en": "Raw broadband voltage",
        "output": "通道 RMS、通道-频率功率图、质量时间线、工频/饱和指标和候选标签",
        "output_en": "Channel RMS, channel-frequency power, a quality timeline, line/clipping metrics, and candidate labels",
        "checks": "先看时间线定位异常发生时段，再用可缩放原始波形和功率谱核实。候选坏通道必须人工确认，不自动删除。",
        "checks_en": "Use the timeline to locate suspicious periods, then verify them in zoomable traces and spectra. Candidate bad channels require confirmation and are not removed automatically.",
        "reference": "SpikeInterface preprocessing: detect_bad_channels, coherence+PSD, and channel grouping",
    },
    {
        "key": "preprocess",
        "title": "03 按分析目标配置预处理",
        "title_en": "03 Preprocessing is not a fixed recipe",
        "why": "Spike 与 LFP 的频段和生物物理意义不同。滤波、重参考和伪迹处理必须按分析对象选择。",
        "why_en": "Spikes and LFPs occupy different bands and have different biophysical meanings. Filtering, referencing, and artifact handling must match the target.",
        "input": "原始电压与坏通道列表",
        "input_en": "Raw voltage and a bad-channel list",
        "output": "AP/sorting 与 LFP 两条分支预览、处理链和运行前安全检查",
        "output_en": "AP/sorting and LFP branch previews, a processing chain, and pre-run safeguards",
        "checks": "确认坏通道后再重参考；Neuropixels 先核对 inter-sample phase shift；避免在 sorter 内外重复 whitening；短片段预览不覆盖原始数据。",
        "checks_en": "Confirm bad channels before referencing, check Neuropixels inter-sample phase shift, avoid whitening both outside and inside the sorter, and remember that previews never overwrite raw data.",
        "reference": "SpikeInterface PreprocessingPipeline, phase_shift, common_reference, and whitening",
    },
    {
        "key": "sorting",
        "title": "04 Spike sorting 与工具选择",
        "title_en": "04 Spike sorting and tool selection",
        "why": "不同 sorter 对电极密度、记录时长和硬件的要求不同。自动输出是候选 unit，不等于可靠单神经元。",
        "why_en": "Sorters differ in probe density, recording duration, and hardware requirements. Automatic output contains candidate units, not guaranteed single neurons.",
        "input": "高采样率多通道记录、探针几何与 sorter 参数",
        "input_en": "High-rate multichannel recording, probe geometry, and sorter parameters",
        "output": "各 sorter 原生文件、统一秒级 Unit/spike 结果、参数、日志与比较证据",
        "output_en": "Native sorter files, normalized Unit/spike times in seconds, parameters, logs, and comparison evidence",
        "checks": "先确认环境状态与探针适用性。Kilosort4 适合高密度探针；MountainSort5 更偏 CPU/tetrode，可选择 Scheme 1/2/3。运行多个 sorter 后检查 Hungarian 匹配、一致度、独有 Unit 和共识 Unit；真实数据的一致度不能称为准确率。",
        "checks_en": "Verify environment and probe suitability first. Kilosort4 targets dense probes; MountainSort5 is CPU/tetrode-oriented and offers Schemes 1/2/3. After multiple runs, inspect Hungarian matches, agreement, unique units, and consensus units; agreement on real data is not accuracy.",
        "reference": "Kilosort4; MountainSort5; SpikeInterface sorter and comparison modules",
    },
    {
        "key": "unit_qc",
        "title": "05 Unit 质控与人工复核",
        "title_en": "05 Unit QC and manual review",
        "why": "Sorter 的 cluster 可能包含噪声、重复 unit 或多单元活动，需要结合多项指标和波形稳定性判断。",
        "why_en": "Clusters can be noise, duplicates, or multi-unit activity. Decisions require several metrics and waveform stability.",
        "input": "Spike times、波形、模板和记录时长",
        "input_en": "Spike times, waveforms, templates, and duration",
        "output": "放电率、ISI 违例、SNR、标签与复核表",
        "output_en": "Firing rate, ISI violations, SNR, labels, and a review table",
        "checks": "点击散点查看 unit 指标；阈值仅作为筛选规则；保留人工修改记录。",
        "checks_en": "Click points to inspect unit metrics. Thresholds are screening rules, not biological truth. Preserve manual decisions.",
        "reference": "SpikeInterface quality metrics; refractory-period contamination",
    },
    {
        "key": "sync",
        "title": "06 TTL、行为与统一时间轴",
        "title_en": "06 TTL, behavior, and a common timeline",
        "why": "事件对齐决定神经活动发生在行为之前还是之后。漏脉冲与时钟漂移不能靠画图掩盖。",
        "why_en": "Synchronization determines whether neural activity precedes or follows behavior. Missing pulses and clock drift cannot be hidden by plotting.",
        "input": "Spike 秒时间、TTL、行为事件和视频帧",
        "input_en": "Spike times in seconds, TTLs, behavioral events, and video frames",
        "output": "统一秒时间轴、匹配残差与 trial 表",
        "output_en": "Common time base, matching residuals, and a trial table",
        "checks": "核对事件数量、顺序、匹配残差、漂移趋势、丢帧和重复脉冲。",
        "checks_en": "Check event counts, order, residuals, drift, dropped frames, and duplicate pulses.",
        "reference": "IBL synchronization and ALF trials object",
    },
    {
        "key": "behavior",
        "title": "07 行为质量先于神经解释",
        "title_en": "07 Behavior quality precedes neural interpretation",
        "why": "Trial 数量、条件平衡、反应时和表现会影响神经统计与解码，必须先独立检查行为。",
        "why_en": "Trial counts, class balance, reaction time, and performance affect neural statistics and decoding and should be inspected first.",
        "input": "Trial 表、条件、选择、反应时和排除规则",
        "input_en": "Trial table, conditions, choices, reaction time, and exclusion rules",
        "output": "条件计数、心理测量曲线、反应时和有效 trial",
        "output_en": "Condition counts, psychometrics, reaction time, and valid trials",
        "checks": "点击曲线点查看刺激水平与样本量；检查缺失值、极端反应时和类别不平衡。",
        "checks_en": "Click curve points to inspect stimulus level and sample size. Check missing data, reaction-time outliers, and imbalance.",
        "reference": "IBL Brain-Wide Map behavioral analyses",
    },
    {
        "key": "analysis",
        "title": "08 神经活动分析工作台",
        "title_en": "08 Neural activity analysis workbench",
        "why": "事件响应、spike train 统计、LFP 频谱和 spike-field 耦合属于不同分析对象，必须保留各自的数据结构、单位和假设。",
        "why_en": "Event responses, spike-train statistics, LFP spectra, and spike-field coupling are distinct analysis objects with different structures, units, and assumptions.",
        "input": "Unit spike times、对齐事件、原始/LFP 电压、分析窗口与条件",
        "input_en": "Unit spike times, alignment events, raw/LFP voltage, windows, and conditions",
        "output": "Raster/PSTH、CV2/Lv/Fano、CCH/STTC/距离、PSD/coherence/时频图、相位锁定和 PAC",
        "output_en": "Raster/PSTH, CV2/Lv/Fano, CCH/STTC/distances, PSD/coherence/time-frequency maps, phase locking, and PAC",
        "checks": "先确认当前选项属于 spike、LFP 还是联合分析；检查分箱、频段、窗口、相位参考和 surrogate 次数；案例结果只验证方法结构。",
        "checks_en": "Identify whether the current view is spike, LFP, or combined analysis. Verify bins, bands, windows, phase reference, and surrogate count. Case-study results validate method structure only.",
        "reference": "Neo data model; Elephant spike-train, spectral, STA and phase APIs; Folschweiller & Sauer (2023) case structure",
    },
    {
        "key": "statistics",
        "title": "09 从图到统计证据",
        "title_en": "09 From figures to statistical evidence",
        "why": "先定义样本单位与重复测量结构，再选择检验。Unit、session 和动物不能随意当作独立样本。",
        "why_en": "Define the sampling unit and repeated-measures structure before choosing a test. Units, sessions, and animals are not automatically independent.",
        "input": "Trial 级指标、条件标签和层级信息",
        "input_en": "Trial-level metrics, condition labels, and hierarchy",
        "output": "样本层级、参数/非参数检验、圆周/置换检验、效应量、置信区间、混合模型和校正值",
        "output_en": "Sampling hierarchy, parametric/nonparametric and circular/surrogate tests, effects, CIs, mixed models, and corrected p-values",
        "checks": "查看正态性、配对关系、方差、伪重复和多重比较；相位数据使用圆周统计并与 circular-shift surrogate 对照；同时报告效应量与置信区间。",
        "checks_en": "Inspect normality, pairing, variance, pseudoreplication, and multiplicity. Use circular statistics and circular-shift surrogates for phase data. Report effects and confidence intervals.",
        "reference": "SciPy/statsmodels; Elephant phase analysis; Folschweiller & Sauer (2023) statistical design",
    },
    {
        "key": "decoding",
        "title": "10 机器学习、聚类与数据泄漏",
        "title_en": "10 Machine learning, clustering, and leakage",
        "why": "解码回答神经活动能否预测标签，不自动证明脑区编码了某个抽象变量。",
        "why_en": "Decoding asks whether neural activity predicts a label; it does not by itself prove abstract coding.",
        "input": "Trial × feature 矩阵、标签和分组变量",
        "input_en": "Trial-by-feature matrix, labels, and grouping variables",
        "output": "多模型交叉验证、AUC/F1、混淆矩阵、置换、PCA 与聚类",
        "output_en": "Multi-model CV, AUC/F1, confusion matrix, permutation, PCA, and clustering",
        "checks": "预处理只在训练折拟合；同一动物/session 用分组拆分；与 shuffle 基线比较；不要挑选最好模型后隐瞒比较过程。",
        "checks_en": "Fit preprocessing inside training folds, group by animal/session, compare against shuffle, and disclose model comparisons.",
        "reference": "IBL Brain-Wide Map decoding analyses; scikit-learn",
    },
    {
        "key": "export",
        "title": "11 论文图与可复现导出",
        "title_en": "11 Publication figures and reproducible export",
        "why": "论文图需要可编辑、可追溯，并能找到输入、参数、统计表、软件版本和人工决定。",
        "why_en": "Publication figures must be editable and traceable to inputs, parameters, statistics, software versions, and manual decisions.",
        "input": "分析对象、统计结果和绘图设置",
        "input_en": "Analysis objects, statistical results, and figure settings",
        "output": "PNG/SVG、绘图数据、Methods、workflow 与 provenance",
        "output_en": "PNG/SVG, plotted data, Methods, workflow, and provenance",
        "checks": "检查坐标和单位、误差定义、颜色可辨识性、统计标注来源，并保留 SVG 和 CSV。",
        "checks_en": "Check axes and units, error definitions, accessible colors, and statistical annotations. Preserve SVG and CSV.",
        "reference": "IBL Brain-Wide Map figure organization and reproducibility",
    },
]


def tutorial_value(chapter: dict, field: str, language: str = "zh_CN") -> str:
    if language == "en_US":
        return chapter.get(f"{field}_en", chapter[field])
    return chapter[field]
