"""Generate website task instructions from the same catalogue as desktop help."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from neuroflow.tutorial_catalog import TUTORIAL_CATALOG, catalog_text


def rst_text(value):
    """Catalogue values are plain text, not reStructuredText directives."""
    for character in ("\\", "*", "`", "_"):
        value = value.replace(character, "\\" + character)
    return value


def build_task_manual():
    for folder, language in (("zh", "zh_CN"), ("en", "en_US")):
        english = language == "en_US"
        title = "Task guide" if english else "按操作查阅"
        lines = [title, "=" * 48, "", ".. This file is generated by scripts/generate_task_manual.py.", "",
                 "These instructions also appear in the desktop Tutorial center." if english else
                 "本页与 App 教程中心共用操作内容。按当前任务选择，具体参数以工作区显示为准。", "",
                 ".. contents:: " + ("On this page" if english else "本页操作"), "   :local:", "   :depth: 1", ""]
        for item in TUTORIAL_CATALOG:
            get = lambda field: rst_text(catalog_text(item, field, language))
            lines += [f'.. _task-{item["id"]}:', "", get("title"), "-" * 100, "", get("summary"), "",
                      "**" + ("Have ready" if english else "先准备好") + "**", "", get("prerequisites"), ""]
            for i, step in enumerate(item["steps"], 1):
                lines += [f'{i}. **{rst_text(catalog_text(step, "title", language))}**', "",
                          "   " + rst_text(catalog_text(step, "body", language)), ""]
            for field, label in (("check", "Check the result" if english else "完成检查"),
                                 ("output", "Saved output" if english else "保存位置")):
                lines += [f"**{label}**", "", get(field), ""]
            for problem in item["troubleshooting"]:
                lines += ["**" + rst_text(catalog_text(problem, "title", language)) + "**", "", rst_text(catalog_text(problem, "body", language)), ""]
            if item["reference"]:
                lines += [f'`{"Method reference" if english else "方法参考"} <{item["reference"]}>`__', ""]
        (ROOT / "docs/sphinx" / folder / "task-guide.rst").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    build_task_manual()
